### ISSUE TITLE
Battery Charging in NiMH/NiCAD mode

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#10]
Because some batteries have no or very little -dV, I would propose that 0.0 V be accepted.
To avoid premature termination of the charging, I would propose that charging stops 1200 sec after the first time the -dV occured.
After that the progam should change to PSU mode with current set to 'Constant Current'/10

**Comment by molenman** [comment]
When end of charge is detected, there is a small discharge current from the battery flowing back to the DPS unit.  I had to put a diode between the DPS unit and the batteries to prevent current flowing back to the DPS unit.

**Comment by lambcutlet** [comment]
Implementing a -dV of 0.0V I think is dangerous and I would not recommend it. However if you insist on this method of charging you could employ PSU mode, but please be careful.
Implementing a timer for fast charging with a switch over to a trickle charge could be possible, but using this style of charging could be problematic as there is no feedback and batteries may accidentally become overcharged, overheated and explode.
Trickle charging could be implemented using PSU mode.

**Comment by lambcutlet** [comment]
close due to no further communication
