### ISSUE TITLE
CSV mode

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#11]
I wold like to change the CSV file during a session. It does not work jet. How do I have to change dps_GUI_program.py to make it possible?

**Comment by lambcutlet** [comment]
I presume you mean File->Open *.CSV file & CSV run.
If 'CSV run' is active with for example 'first_run.CSV'. Whilst this is in progress you can File->Open 'second_run.CSV' overwriting 'first_run.CSV'. CSV run will continue to the end of the 'second_run.CSV' file.
is this what you mean?

**Comment by lambcutlet** [comment]
close due to no further communication
