### ISSUE TITLE
errors when i try to start program...

### ISSUE THREAD

**Issue by mega-hz** [lambcutlet/DPS5005_pyGUI#17]
Hi,

i am sorry but i cant start your program, getting errors:

~/DPS5005_pyGUI/source_files $ python dps_GUI_program.py
Traceback (most recent call last):
  File "dps_GUI_program.py", line 4, in <module>
    import serial
  File "/usr/local/lib/python2.7/dist-packages/serial/__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "/usr/local/lib/python2.7/dist-packages/serial/model.py", line 1291
    exec(source, namespace)
SyntaxError: unqualified exec is not allowed in function 'from_meta' it contains a nested function with free variables

can you help me getting this running?
My System is Linux Mint 17,3 Cinnamon... 64Bit.

regards & thanks,
Wolfram.

**Comment by mega-hz** [comment]
yes, serial is installed...


-----------------------------------------

mega-hz@MacBookPro ~ $ sudo pip install serial
[sudo] password for mega-hz:
Requirement already satisfied (use --upgrade to upgrade): serial in /usr/local/lib/python2.7/dist-packages
Cleaning up...
mega-hz@MacBookPro ~ $ sudo pip install serial --upgrade
Downloading/unpacking serial from https://files.pythonhosted.org/packages/e9/61/99cef392aff196f021f279c8c2a9c040a38c38c3ca5e0ae34e2d9a42941a/serial-0.0.96-py2.py3-none-any.whl#sha256=4634227d294207a74f8ce55dc96a34132c77f0fd9958e10f92986d67ed68c40d
  Downloading serial-0.0.96-py2.py3-none-any.whl (40kB): 40kB downloaded
Requirement already up-to-date: future>=0.17.1 in /usr/local/lib/python2.7/dist-packages (from serial)
Requirement already up-to-date: iso8601>=0.1.12 in /usr/local/lib/python2.7/dist-packages (from serial)
Requirement already up-to-date: pyyaml>=3.13 in /usr/local/lib/python2.7/dist-packages (from serial)
Installing collected packages: serial
  Found existing installation: serial 0.0.91
    Uninstalling serial:
      Successfully uninstalled serial
Compiling /tmp/pip_build_root/serial/serial/model.py ...
SyntaxError: unqualified exec is not allowed in function 'from_meta' it contains a nested function with free variables (model.py, line 1291)

Successfully installed serial
Cleaning up...
mega-hz@MacBookPro ~ $ cd DPS5005_pyGUI/source_files/
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ python dps_GUI_program.py
Traceback (most recent call last):
  File "dps_GUI_program.py", line 4, in <module>
    import serial
  File "/usr/local/lib/python2.7/dist-packages/serial/__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "/usr/local/lib/python2.7/dist-packages/serial/model.py", line 1291
    exec(source, namespace)
SyntaxError: unqualified exec is not allowed in function 'from_meta' it contains a nested function with free variables
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $

--------------------------------------------------------------------------

this is what i get...

**Comment by lambcutlet** [comment]
this may be a stupid question 
but could you try 'sudo python dps_GUI_program.py'

**Comment by mega-hz** [comment]
well, the same error....

mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ sudo python dps_GUI_program.py
[sudo] password for mega-hz: 
Traceback (most recent call last):
  File "dps_GUI_program.py", line 4, in <module>
    import serial
  File "/usr/local/lib/python2.7/dist-packages/serial/__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "/usr/local/lib/python2.7/dist-packages/serial/model.py", line 1291
    exec(source, namespace)
SyntaxError: unqualified exec is not allowed in function 'from_meta' it contains a nested function with free variables
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ 

is it ok with python 2.7?

**Comment by lambcutlet** [comment]
I installed the files on my laptop running python 2.7.15 and had issues with minimalmodbus 'AttributeError: 'module' object has no attribute 'PARITY_NONE''
anyway I solved it by removing serial and only installing pyserial. Maybe you have similar issues.
Could you remove serial 'pip uninstall serial' and ensure you only have pyserial installed 'pip install pyserial'
if this works I'll need to change the installation requirements

**Comment by lambcutlet** [comment]
I don't use Linux Mint but you may need to install PyQt5 like this: 'sudo apt-get install python-pyqt5'

**Comment by mega-hz** [comment]
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ sudo pip install PyQt5
Downloading/unpacking PyQt5
  Could not find any downloads that satisfy the requirement PyQt5
Cleaning up...
No distributions at all found for PyQt5
Storing debug log for failure in /home/mega-hz/.pip/pip.log
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ sudo apt-get install python-pyqt5
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket python-pyqt5 kann nicht gefunden werden.


i checked in the desktop apps and there is python3-pyqt5 installed...

**Comment by lambcutlet** [comment]
That's for python version 3
If you perform 'apt-cache search pyqt5' 
do you get any options that doesn't contain python3?

**Comment by mega-hz** [comment]
loks like a mixed python installation?? 
should i remove all python3 stuff?

**Comment by mega-hz** [comment]
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $ apt-cache search pyqt5
pyqt5-dev - Development files for PyQt5
pyqt5-doc - Documentation for PyQt5
pyqt5-examples - Examples and demos for PyQt5
python3-dbus.mainloop.pyqt5 - D-Bus Support for PyQt5 with Python 3
python3-dbus.mainloop.pyqt5-dbg - D-Bus Support for PyQt5 (debug extensions for Python 3)
python3-pyqt5 - Python 3 bindings for Qt5
python3-pyqt5-dbg - Python 3 bindings for Qt5 (debug extensions)
python3-pyqt5.qtmultimedia - Python 3 bindings for Qt5's Multimedia module
python3-pyqt5.qtmultimedia-dbg - Python 3 bindings for Qt5's Multimedia module (debug extensions)
python3-pyqt5.qtopengl - Python 3 bindings for Qt5's OpenGL module
python3-pyqt5.qtopengl-dbg - Python 3 bindings for Qt5's OpenGL module (debug extension)
python3-pyqt5.qtpositioning - Python 3 bindings for QtPositioning module
python3-pyqt5.qtpositioning-dbg - Python 3 bindings for QtPositioning module (debug extension)
python3-pyqt5.qtquick - Python 3 bindings for QtQuick module
python3-pyqt5.qtquick-dbg - Python 3 bindings for QtQuick module (debug extension)
python3-pyqt5.qtsensors - Python 3 bindings for QtSensors module
python3-pyqt5.qtsensors-dbg - Python 3 bindings for QtSensors module (debug extension)
python3-pyqt5.qtserialport - Python 3 bindings for QtSerialPort module
python3-pyqt5.qtserialport-dbg - Python 3 bindings for QtSerialPort module (debug extension)
python3-pyqt5.qtsql - Python 3 bindings for Qt5's SQL module
python3-pyqt5.qtsql-dbg - Python 3 bindings for Qt5's SQL module (debug extension)
python3-pyqt5.qtsvg - Python 3 bindings for Qt5's SVG module
python3-pyqt5.qtsvg-dbg - Python 3 bindings for Qt5's SVG module (debug extension)
python3-pyqt5.qtwebkit - Python 3 bindings for Qt5's WebKit module
python3-pyqt5.qtwebkit-dbg - Python 3 bindings for Qt5's WebKit module (debug extensions)
python3-pyqt5.qtx11extras - Python 3 bindings for QtX11Extras module
python3-pyqt5.qtx11extras-dbg - Python 3 bindings for QtX11Extras module (debug extension)
python3-pyqt5.qtxmlpatterns - Python 3 bindings for Qt5's XmlPatterns module
python3-pyqt5.qtxmlpatterns-dbg - Python 3 bindings for Qt5's XmlPatterns module (debug extension)
pyqt5-dev-tools - Development tools for PyQt5
python3-pyqt5.qsci - Python 3 bindings for QScintilla 2 with Qt 5
mega-hz@MacBookPro ~/DPS5005_pyGUI/source_files $

**Comment by lambcutlet** [comment]
You could try installing pyqt5-dev to see if that pulls in the files that does requires.
Failing that your next best option maybe to use python3.
I'll download a live version of mint. And try the install. I'll update you tomorrow.

**Comment by mega-hz** [comment]
ok, thank you very much

**Comment by mega-hz** [comment]
installing pyqt5-dev failed too...

I really like the cinnamon desktop, so what linux do you use? debian?
is it possible to use cinnamon under debian?

**Comment by mega-hz** [comment]
well, that is not importend...
maybe you can convert your program to python3?

Would it be possible to add Bluetouth to your program beside serial?
The DPS5020 has also a bluetouth , would be great to use that.

**Comment by lambcutlet** [comment]
Wolfram, I managed to get the program to work using a liveUSB copy of Linux Mint 64bit with cinnamon
the live version is missing a few files. 
this has python version 2.7.15rc1.
So here we go:
1. sudo apt-get install python-pip   (python-pip - is probably installed already)
2. sudo pip install pyserial
3. sudo apt-get install python-setuptools   (python-setuptools - is probably installed already)
4. sudo pip install minimalmodbus
5. sudo apt-get install python-pyqt5
6. sudo apt-get install python-pyqtgraph
and finally
7. python dps_GUI_program.py

Bluetooth once connected will appear as a serial port. So yes, you can use this program with bluetooth.

**Comment by mega-hz** [comment]
Linux Mint 17.3 ?

**Comment by lambcutlet** [comment]
it was Linux Mint 19.1 but I would expect 17.3 to work.
give it a try, then let me know if it worked or failed.

**Comment by mega-hz** [comment]
ok, i'll try in about 30min.

if it dont work, i will try the live-cd too and maybe upgrade my laptop...

**Comment by mega-hz** [comment]
under linux mint 17.3 always the same errors,
trying 19.1 now...

**Comment by lambcutlet** [comment]
I downloaded 17.3 it does not contain or allow you to install PyQt5 easily.
others have also had issues
[https://github.com/muammar/mkchromecast/issues/201](url)
and the recommendation was to upgrade

**Comment by mega-hz** [comment]
hi,

after booting the 19,1 it runs!!

well, i hope i can upgrade from 17,3 to 18 to 19,1 ....
can you please also try to get it run with python3 please?

**Comment by mega-hz** [comment]
I have installed Linux Cinnamon 19.1 64Bit and your fine program is working!

Thank you for helping!
Where can i donate you? :-)

**Comment by mega-hz** [comment]
i installed Linux Mint Cinnamon 19.1 successfully and all requirements,
now your program is wworking fine!
Didnt try it on the DPS yet, because it is not ready build in a case.

I would like to donate your help and effort!
Thank you!!!

**Comment by lambcutlet** [comment]
I'm glad you got it working
have fun. :)

**Comment by lambcutlet** [comment]
Wolfram,
Update for you
If you install all the requirements based on python3, the program works.
I've updated the list below based on python3, but they are a guess as Fedora is my preferred OS where the install names are slightly different. 

1. sudo apt-get install python3-pip   (python3-pip - is probably installed already)
2. sudo pip3 install pyserial
3. sudo apt-get install python3-setuptools   (python-setuptools - is probably installed already)
4. sudo pip3 install minimalmodbus
5. sudo apt-get install python3-pyqt5
6. sudo apt-get install python3-pyqtgraph
  and finally
7. python3 dps_GUI_program.py

**Comment by mega-hz** [comment]
ok, i will try it!

**Comment by mega-hz** [comment]
instead of
**sudo apt-get install python3-pyqtgraph** (cannot be found)
there must be 
**pip3 install pyqtgraph**

but still not working under Linux Mint 17.3 :-(
Have to stay at Linux Mint 19.1 i guess.

**Comment by lambcutlet** [comment]
Hi, I too tried Mint 17.3 using python3 install and it failed with pyqtgraph.
It appears that an upgrade is your best way forward.

**Comment by mega-hz** [comment]
ok, i will try it!

**Comment by mega-hz** [comment]
didn't work too...
