### ISSUE TITLE
CSV run

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#6]
Thank you for your mail.
I tried to load and run a *.CSV file by clicking 'CSV run', but nothing happened.

**Comment by lambcutlet** [comment]
You need to enable the output then perform CSV run

steps required:
1. File -> Open -> select the 'Sample.csv' file. 'Steps remaining:' in the bottom left hand corner will then contain a number.
3. bottom right hand corner switch output ON
4. then finally begin 'CSV run'

**Comment by HBerecz** [comment]
Thank you.
'CSV run' is a very interesting function that I will use sooner or later.
Could you also imlement a function e.g. 'CSV show' that shows the plot of a formerly saved plot?
