### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#7]
Thank you.
As I work extensively with AutoHotkey, I would prefer to work with hotkeys instead of mouseclicks.
Is it possible to assign hotkeys to certain functions, e.g. Ctrl+S for 'Save Plot'?

**Comment by lambcutlet** [comment]
been playing around with a personal copy of the program
so far i have implemented:
('Save Plot - CTRL+S')
('Clear Plot - CTRL+L')
('Toggle Lock - CTRL+ALT+L')
('File Open - CTRL+O')
('Quit application - CTRL+Q')

i have tried to make them as generic as possible matching other programs. 
buttons like 'connect' & 'on/off' however are more difficult to find general keyboard commands.
for the moment i think i'll leave the unusual buttons as mouse clicks.
i'll create a branch over the weekend with these hotkeys added.

**Comment by HBerecz** [comment]
could you send me your personal copy of the program? Thank you.

**Comment by lambcutlet** [comment]
attached is a copy of my files which I have slowly been updating to incorporate your request '#8' to have a CSV viewer.
CSV files can be opened and viewed when the serial port is not connected.
these files are a work in progress so expect issues.
May I ask, What do you use the Power Supply for?

I'll need a couple of weeks to tidy these files up and up issue this version for everyone to use.

[personal_copy_30-08-2018.zip](https://github.com/lambcutlet/DPS5005_pyGUI/files/2337754/personal_copy_30-08-2018.zip)

**Comment by HBerecz** [comment]
I use the Power Supply for loading NiMH-battery charging.
The new files work perfectly, I only had to move the Colours from [SectionThree] to [SectionOne] to avoid the AttributeError: 'Import_limits' object has no attribute 'background_colour'.

**Comment by lambcutlet** [comment]
That's odd, I get no warning on my system.
I wonder what's different

**Comment by HBerecz** [comment]
I tried it again with the same result: AttributeError: 'Import_limits' object has no attribute 'background_colour'.
I use Windows 10 and Python 3.6.6 (sys.version = 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)])

**Comment by lambcutlet** [comment]
Strange 
A friend installed python 3.7 on Windows 7 installed the required files and ran the program there were no warnings or errors.
Myself I installed it on a windows 10 laptop with python 3.6.5, installed the required files in this order:
`py -m pip install serial`
`py -m pip install minimalmodbus`
`py -m pip install pyqt5`
`py -m pip install pyqtgraph`
ran the program with:
`py dps_GUI_program.py`
And no errors. 
I'm sorry to say but there must be something funny with your setup. Could I suggest you start from afresh and install each of the required files in sequence.

**Comment by HBerecz** [comment]
With your newest files it works, I don't know why. Thank you.
