### ISSUE TITLE
white background for the plot

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#9]
I prefer a white background for the plot. Therefore I inserted in my personal copy of dps_GUI_program.py
"pg.setConfigOption('background', 'w')" after the line "import pyqtgraph as pg".
for better visibility I changed the colour of the x axis to dark green, i.e. '0a0'
self.p1.setLabel('bottom', 'Time', units='s', color='0a0', **{'font-size':'10pt'})
self.p1.getAxis('bottom').setPen(pg.mkPen(color='0a0', width=1)),
the Y1 axis and pen1 to blue (color='b'), the Y2 axis and pen2  to red (color='r')
so that they conform with the german conventions for voltage and current.
If you find these changes interesting, you can of course implement them in your official version.
Unfortunately I did not find the option for reducing the space between the axes and the plot.
Perhaps you can help me.

[dps_GUI_program.zip](https://github.com/lambcutlet/DPS5005_pyGUI/files/2123600/dps_GUI_program.zip)

**Comment by lambcutlet** [comment]
i've added a manual way to change the colours using the 'dps5005_limits.ini' file.
have a look in the branch section, its currently configured with your colour choice for the moment.
i haven't found a way to reduce the space between axes and plot but i'll keep looking.
